[api]
# Get your API key from: https://platform.openai.com/api-keys
key = ""

[chat]
# For details see: https://platform.openai.com/docs/api-reference/chat
model = "gpt-4o"
max_tokens = { value = 4096, min = 128, max = 4096, step = 128 }
temperature = { value = 1.0, min = 0.0, max = 1.0, step = 0.05 }
top_p = { value = 1.0, min = 0.0, max = 1.0, step = 0.05 }
frequency_penalty = { value = 0.0, min = -2.0, max = 2.0, step = 0.05 }
presence_penalty = { value = 0.0, min = -2.0, max = 2.0, step = 0.05 }

[ui]
editor_command = ["gedit", "--standalone"]

[ui.layout]
prompt_size = 8

[ui.colors]
conversation.background = "#020414"
conversation.foreground = "#33DD88"
conversation_names = "#DD4400"
prompt.background = "#110000"
prompt.foreground = "#DDCC04"
config.background = "#020414"
config.foreground = "#FF5511"
debug.background = "#020414"
debug.foreground = "#5511FF"

[hotkeys]
quit_program = [ "ctrl q" ]
select = [ "enter" ]
cancel = [ "esc" ]
new = [ "ctrl n" ]
clear = [ "ctrl c" ]
selection_up = [ "up" ]
selection_down = [ "down" ]
scroll_up = [ "pgup" ]
scroll_down = [ "pgdn" ]
increment = [ "ctrl up", "="]
decrement = [ "ctrl down", "-"]
cycle_tab = [ "tab" ]
view_conversation_tab = [ "f1" ]
view_conversation_history_tab = [ "f2" ]
view_config_tab = [ "f8" ]
view_debug_tab = [ "f9" ]
send_prompt = [ "alt enter" ]
get_message_from_editor = [ "alt e" ]

[[system.instructions]]
name = "simple"
message = """
You are a helpful assistant.
Do not bother being polite. Your responses should be concise and terse.
"""

[[system.instructions]]
name = "detailed"
message = """
You are a helpful assistant.
Do not bother being polite. Your responses should be detailed.
"""

[[system.instructions]]
name = "funny"
message = """
You are a funny assistant.
Do not bother being polite. Your responses should be funny.
"""
