# Supported providers include: "openai", "anthropic"
provider = "openai"

[keys]
# Get your OpenAI API key from: https://platform.openai.com/api-keys
openai = ""
# Get your Anthropic API key from: https://console.anthropic.com/settings/keys
anthropic = ""

[ui.layout]
prompt_size = 8

# Base palette: #1C1678 #8576FF #7BC9FF #A3FFD6 #D37C31
[ui.colors.background]
normal = "#04003C"
inactive = "#04003C"
highlight = "#2A21B4"
title = "#04003C"
warn = "#6A3100"
[ui.colors.text]
normal = "#7BC9FF"
inactive = "#4D7E9F"
highlight = "#11FF55"
title = "#11FFBB"
warn = "#D37C31"
[ui.colors.frame]
normal = "#8576FF"
inactive = "#423B80"
highlight = "#8576FF"
title = "#A398FF"
warn = "#D37C31"
[ui.colors.widget]
normal = "#7ABFA0"
inactive = "#123313"
highlight = "#7ABFA0"
title = "#7ABFA0"
warn = "#D37C31"
[ui.colors.cursor]
normal = "#9CD6FF"
inactive = "#223333"
highlight = "#9CD6FF"
title = "#9CD6FF"
warn = "#D37C31"

[commands]
editor = ["gedit", "--standalone"]
copy = ["xsel", "-ib"]

[hotkeys]
quit_program = [ "ctrl q" ]
new = [ "ctrl n" ]
open = [ "ctrl o" ]
edit = [ "alt e" ]
copy = [ "ctrl c" ]
clear = [ "ctrl delete" ]
refresh = [ "f5" ]
confirm = [ "alt enter" ]
select = [ "enter" ]
cancel = [ "esc" ]
selection_up = [ "up" ]
selection_down = [ "down" ]
selection_start = [ "home" ]
selection_end = [ "end" ]
scroll_up = [ "pgup" ]
scroll_down = [ "pgdn" ]
increment = [ "ctrl up", "="]
decrement = [ "ctrl down", "-"]
cycle_tab = [ "tab" ]
cycle_back_tab = [ "backtab", "shift backtab", "shift tab" ]
view_conversation_tab = [ "f1" ]
view_config_tab = [ "f2" ]
view_debug_tab = [ "f3" ]

[[system.instructions]]
name = "Quick"
message = """
You are a helpful assistant.
Do not bother being polite. Your responses should be concise and terse.
"""

[[system.instructions]]
name = "Detailed"
message = """
You are a helpful assistant.
Do not bother being polite. Your responses should be detailed.
"""

[[system.instructions]]
name = "Funny"
message = """
You are a funny assistant.
Do not bother being polite. Your responses should be funny.
"""
