# Supported providers include: "openai", "anthropic"
provider = "openai"

[keys]
# Get your OpenAI API key from: https://platform.openai.com/api-keys
openai = ""
# Get your Anthropic API key from: https://console.anthropic.com/settings/keys
anthropic = ""

[ui]
prompt_size = 8
theme = "default"

[commands]
editor = ["gedit", "--standalone"]
copy = ["xsel", "-ib"]

[hotkeys]
quit_program = ["ctrl q"]
new = ["ctrl n"]
open = ["ctrl o"]
edit = ["alt e"]
copy = ["ctrl c"]
clear = ["ctrl delete"]
refresh = ["f5"]
confirm = ["alt enter"]
select = ["enter"]
cancel = ["esc"]
selection_up = ["up"]
selection_down = ["down"]
selection_start = ["home"]
selection_end = ["end"]
selection_previous = ["left"]
selection_next = ["right"]
scroll_up = ["pgup"]
scroll_down = ["pgdn"]
increment = ["ctrl up", "="]
decrement = ["ctrl down", "-"]
cycle_tab = ["tab"]
cycle_back_tab = ["backtab", "shift backtab", "shift tab"]

[[system.instructions]]
name = "Quick"
message = """
You are a helpful assistant.
Do not bother being polite. Your responses should be concise and terse.
"""

[[system.instructions]]
name = "Detailed"
message = """
You are a helpful assistant.
Do not bother being polite. Your responses should be detailed.
"""

[[system.instructions]]
name = "Funny"
message = """
You are a funny assistant.
Do not bother being polite. Your responses should be funny.
"""
