background = "#111111"
text = "#ffffff"
text_inactive = "#aaaaaa"
text_warn = "#ff3300"
name = "#0088ff"
name_inactive = "#0044aa"
title = "#66ff66"
frame = "#6666cc"
frame_inactive = "#333388"
tab_selected = "#00ffff"
tab_unselected = "#55bbbb"
input_text = "#ffffff"
input_text_inactive = "#aaaaaa"
cursor = "#dddd00"
cursor_inactive = "#666600"
