# For details see: https://docs.anthropic.com/en/api/messages

[[models]]
id = "claude-3-5-sonnet-latest"
name = "Claude 3.5 Sonnet"
temperature = { value = 0.5, min = 0.0, max = 1.0, step = 0.05 }
max_tokens = { value = 8192, min = 128, max = 8192, step = 128 }
