# For details see: https://platform.openai.com/docs/api-reference/chat

[[models]]
id = "gpt-4o"
name = "GPT-4o"
temperature = { value = 1.0, min = 0.0, max = 2.0, step = 0.05 }
top_p = { value = 1.0, min = 0.0, max = 1.0, step = 0.05 }
frequency_penalty = { value = 0.0, min = -2.0, max = 2.0, step = 0.05 }
presence_penalty = { value = 0.0, min = -2.0, max = 2.0, step = 0.05 }
max_tokens = { value = 16384, min = 128, max = 16384, step = 128 }

[[models]]
id = "gpt-4o-mini"
name = "GPT-4o mini"
temperature = { value = 1.0, min = 0.0, max = 2.0, step = 0.05 }
top_p = { value = 1.0, min = 0.0, max = 1.0, step = 0.05 }
frequency_penalty = { value = 0.0, min = -2.0, max = 2.0, step = 0.05 }
presence_penalty = { value = 0.0, min = -2.0, max = 2.0, step = 0.05 }
max_tokens = { value = 16384, min = 128, max = 16384, step = 128 }
